blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸ì´ë‚˜ í† ë¡ ì´ í•„ìš”í•˜ì‹ ê°€ìš”?
    url: https://github.com/cloud-club/08th-docker-k8s/discussions
    about: ì§ˆë¬¸, í† ë¡ , í•™ìŠµ ê´€ë ¨ ë‚´ìš©ì€ GitHub Discussionsë¥¼ ì´ìš©í•´ì£¼ì„¸ìš”
  - name: ğŸ“š í•™ìŠµ ìë£Œ ê³µìœ 
    url: https://github.com/cloud-club/08th-docker-k8s/discussions/categories/general
    about: í•™ìŠµ ìë£Œë‚˜ ìœ ìš©í•œ ë§í¬ë¥¼ ê³µìœ í•´ì£¼ì„¸ìš”